version: "3.7"

x-app-config: &app-config
  DJANGO_ENV: dev
  DJANGO_SECRET_KEY: secret_key
  COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
  POST_SERVER_ITEM_ACCESS_TOKEN: ${POST_SERVER_ITEM_ACCESS_TOKEN}
  EMAIL_USE_SSL: ${EMAIL_USE_SSL}
  EMAIL_USE_TLS: ${EMAIL_USE_TLS}
  EMAIL_HOST: ${EMAIL_HOST}
  EMAIL_HOST_USER: ${EMAIL_HOST_USER}
  EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
  EMAIL_PORT: ${EMAIL_PORT}
  REDIS_HOST: ${REDIS_HOST}
  REDIS_PORT: ${REDIS_PORT}

x-db-config: &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: postgres


services:
  api:
    image: task_manager_api
    build:
      context: .
    environment:
      <<: *app-config
      <<: *db-config
    depends_on:
      - db
      - celery
      - redis
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

  db:
    image: postgres:12.5-alpine
    environment: *db-config
    logging:
      driver: none
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    environment:
      <<: *app-config
    ports:
    - "6379:6379"

  celery:
    build: .
    command: celery --app=task_manager worker --loglevel=info
    environment:
      <<: *app-config
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  sqlvolume:
