# Generated by Django 4.1.1 on 2022-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_user_managers_remove_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(
                default=[0], related_name="Tag", to="main.tag", verbose_name="Tag"
            ),
        ),
    ]
