# Generated by Django 4.1.1 on 2022-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_task_executor_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Developer', max_length=255, verbose_name='Role'),
        ),
    ]
