# Generated by Django 4.1.1 on 2022-10-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_user_options_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
