# Generated by Django 4.1.1 on 2022-11-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tag",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="Tag", to="main.tag", verbose_name="Tag"
            ),
        ),
    ]
