# Generated by Django 4.1.1 on 2022-10-06 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="task",
            name="executor",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="task_assignee",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("in_development", "In Development"),
                    ("in_qa", "In Qa"),
                    ("in_code_review", "In Code Review"),
                    ("ready_for_release", "Ready For Release"),
                    ("released", "Released"),
                    ("archived", "Archived"),
                ],
                default="new",
                max_length=255,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Developer", "Developer"),
                    ("Manager", "Manager"),
                    ("Admin", "Admin"),
                ],
                default="Developer",
                max_length=255,
                verbose_name="Role",
            ),
        ),
    ]
