# Generated by Django 4.1.3 on 2022-11-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_task_tag_task_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.AddField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="Tag",
                to="main.tag",
                verbose_name="Tag",
            ),
        ),
    ]
