# Generated by Django 4.1.1 on 2022-10-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
    ]
