# Generated by Django 4.1.3 on 2022-11-09 23:30

from django.db import migrations, models
import task_manager.main.services.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_task_tags_task_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_picture",
            field=models.ImageField(
                null=True,
                storage=task_manager.main.services.storage_backends.public_storage,
                upload_to="",
            ),
        ),
    ]
