# Generated by Django 4.1.3 on 2023-02-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_user_avatar_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tag",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="Tag",
                to="main.tag",
                verbose_name="Tag",
            ),
        ),
    ]
