# Generated by Django 4.1.1 on 2022-10-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_task_assignee_alter_task_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="title",
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
