# Generated by Django 4.1.1 on 2022-10-06 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, related_name='task_tag', to='main.tag'),
        ),
    ]
