# Generated by Django 4.1.1 on 2022-10-09 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_tag_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                related_name="Tag", to="main.tag", verbose_name="Tag"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="task_assignee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignee",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="task_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
    ]
