# Generated by Django 4.1.1 on 2022-10-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_task_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
    ]
